### ISSUE TITLE
Reply to the post that made a user progress to the next PCA club

### ISSUE THREAD

**Issue by 33mhz** [hutattedonmyarm/pcabot#3]

**Comment by hutattedonmyarm** [comment]
I like it!

**Comment by hutattedonmyarm** [comment]
@33mhz The post_count of the user object seems to include deleted posts, did I get that right? If so I'd have to take that into account in case the post which made them progress is a deleted one

**Comment by 33mhz** [comment]
@hutattedonmyarm it does. You can take it into account or not (if it's deleted, just create a new post instead, or you can just reply to it anyway).
